<?php

namespace Database\Seeders;

use App\Models\Provinsi;
use App\Models\KabupatenKota;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KabupatenKotaSeeder extends Seeder
{
    /**
    * Run the database seeds.
    */
    public function run(): void
    {
        
        $refKabupatenKota = [
            ["kode" => "1101", "kode_provinsi" => "11", "nama" => "KABUPATEN SIMEULUE"],
            [
                "kode" => "1102",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH SINGKIL",
            ],
            [
                "kode" => "1103",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH SELATAN",
            ],
            [
                "kode" => "1104",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH TENGGARA",
            ],
            [
                "kode" => "1105",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH TIMUR",
            ],
            [
                "kode" => "1106",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH TENGAH",
            ],
            [
                "kode" => "1107",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH BARAT",
            ],
            [
                "kode" => "1108",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH BESAR",
            ],
            ["kode" => "1109", "kode_provinsi" => "11", "nama" => "KABUPATEN PIDIE"],
            ["kode" => "1110", "kode_provinsi" => "11", "nama" => "KABUPATEN BIREUEN"],
            [
                "kode" => "1111",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH UTARA",
            ],
            [
                "kode" => "1112",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH BARAT DAYA",
            ],
            [
                "kode" => "1113",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN GAYO LUES",
            ],
            [
                "kode" => "1114",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH TAMIANG",
            ],
            [
                "kode" => "1115",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN NAGAN RAYA",
            ],
            [
                "kode" => "1116",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN ACEH JAYA",
            ],
            [
                "kode" => "1117",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN BENER MERIAH",
            ],
            [
                "kode" => "1118",
                "kode_provinsi" => "11",
                "nama" => "KABUPATEN PIDIE JAYA",
            ],
            ["kode" => "1171", "kode_provinsi" => "11", "nama" => "KOTA BANDA ACEH"],
            ["kode" => "1172", "kode_provinsi" => "11", "nama" => "KOTA SABANG"],
            ["kode" => "1173", "kode_provinsi" => "11", "nama" => "KOTA LANGSA"],
            ["kode" => "1174", "kode_provinsi" => "11", "nama" => "KOTA LHOKSEUMAWE"],
            ["kode" => "1175", "kode_provinsi" => "11", "nama" => "KOTA SUBULUSSALAM"],
            ["kode" => "1201", "kode_provinsi" => "12", "nama" => "KABUPATEN NIAS"],
            [
                "kode" => "1202",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN MANDAILING NATAL",
            ],
            [
                "kode" => "1203",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN TAPANULI SELATAN",
            ],
            [
                "kode" => "1204",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN TAPANULI TENGAH",
            ],
            [
                "kode" => "1205",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN TAPANULI UTARA",
            ],
            [
                "kode" => "1206",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN TOBA SAMOSIR",
            ],
            [
                "kode" => "1207",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN LABUHAN BATU",
            ],
            ["kode" => "1208", "kode_provinsi" => "12", "nama" => "KABUPATEN ASAHAN"],
            [
                "kode" => "1209",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN SIMALUNGUN",
            ],
            ["kode" => "1210", "kode_provinsi" => "12", "nama" => "KABUPATEN DAIRI"],
            ["kode" => "1211", "kode_provinsi" => "12", "nama" => "KABUPATEN KARO"],
            [
                "kode" => "1212",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN DELI SERDANG",
            ],
            ["kode" => "1213", "kode_provinsi" => "12", "nama" => "KABUPATEN LANGKAT"],
            [
                "kode" => "1214",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN NIAS SELATAN",
            ],
            [
                "kode" => "1215",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN HUMBANG HASUNDUTAN",
            ],
            [
                "kode" => "1216",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN PAKPAK BHARAT",
            ],
            ["kode" => "1217", "kode_provinsi" => "12", "nama" => "KABUPATEN SAMOSIR"],
            [
                "kode" => "1218",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN SERDANG BEDAGAI",
            ],
            [
                "kode" => "1219",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN BATU BARA",
            ],
            [
                "kode" => "1220",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN PADANG LAWAS UTARA",
            ],
            [
                "kode" => "1221",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN PADANG LAWAS",
            ],
            [
                "kode" => "1222",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN LABUHAN BATU SELATAN",
            ],
            [
                "kode" => "1223",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN LABUHAN BATU UTARA",
            ],
            [
                "kode" => "1224",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN NIAS UTARA",
            ],
            [
                "kode" => "1225",
                "kode_provinsi" => "12",
                "nama" => "KABUPATEN NIAS BARAT",
            ],
            ["kode" => "1271", "kode_provinsi" => "12", "nama" => "KOTA SIBOLGA"],
            ["kode" => "1272", "kode_provinsi" => "12", "nama" => "KOTA TANJUNG BALAI"],
            [
                "kode" => "1273",
                "kode_provinsi" => "12",
                "nama" => "KOTA PEMATANG SIANTAR",
            ],
            ["kode" => "1274", "kode_provinsi" => "12", "nama" => "KOTA TEBING TINGGI"],
            ["kode" => "1275", "kode_provinsi" => "12", "nama" => "KOTA MEDAN"],
            ["kode" => "1276", "kode_provinsi" => "12", "nama" => "KOTA BINJAI"],
            [
                "kode" => "1277",
                "kode_provinsi" => "12",
                "nama" => "KOTA PADANGSIDIMPUAN",
            ],
            ["kode" => "1278", "kode_provinsi" => "12", "nama" => "KOTA GUNUNGSITOLI"],
            [
                "kode" => "1301",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN KEPULAUAN MENTAWAI",
            ],
            [
                "kode" => "1302",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN PESISIR SELATAN",
            ],
            ["kode" => "1303", "kode_provinsi" => "13", "nama" => "KABUPATEN SOLOK"],
            [
                "kode" => "1304",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN SIJUNJUNG",
            ],
            [
                "kode" => "1305",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN TANAH DATAR",
            ],
            [
                "kode" => "1306",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN PADANG PARIAMAN",
            ],
            ["kode" => "1307", "kode_provinsi" => "13", "nama" => "KABUPATEN AGAM"],
            [
                "kode" => "1308",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN LIMA PULUH KOTA",
            ],
            ["kode" => "1309", "kode_provinsi" => "13", "nama" => "KABUPATEN PASAMAN"],
            [
                "kode" => "1310",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN SOLOK SELATAN",
            ],
            [
                "kode" => "1311",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN DHARMASRAYA",
            ],
            [
                "kode" => "1312",
                "kode_provinsi" => "13",
                "nama" => "KABUPATEN PASAMAN BARAT",
            ],
            ["kode" => "1371", "kode_provinsi" => "13", "nama" => "KOTA PADANG"],
            ["kode" => "1372", "kode_provinsi" => "13", "nama" => "KOTA SOLOK"],
            ["kode" => "1373", "kode_provinsi" => "13", "nama" => "KOTA SAWAH LUNTO"],
            [
                "kode" => "1374",
                "kode_provinsi" => "13",
                "nama" => "KOTA PADANG PANJANG",
            ],
            ["kode" => "1375", "kode_provinsi" => "13", "nama" => "KOTA BUKITTINGGI"],
            ["kode" => "1376", "kode_provinsi" => "13", "nama" => "KOTA PAYAKUMBUH"],
            ["kode" => "1377", "kode_provinsi" => "13", "nama" => "KOTA PARIAMAN"],
            [
                "kode" => "1401",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN KUANTAN SINGINGI",
            ],
            [
                "kode" => "1402",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN INDRAGIRI HULU",
            ],
            [
                "kode" => "1403",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN INDRAGIRI HILIR",
            ],
            [
                "kode" => "1404",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN PELALAWAN",
            ],
            ["kode" => "1405", "kode_provinsi" => "14", "nama" => "KABUPATEN S I A K"],
            ["kode" => "1406", "kode_provinsi" => "14", "nama" => "KABUPATEN KAMPAR"],
            [
                "kode" => "1407",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN ROKAN HULU",
            ],
            [
                "kode" => "1408",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN BENGKALIS",
            ],
            [
                "kode" => "1409",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN ROKAN HILIR",
            ],
            [
                "kode" => "1410",
                "kode_provinsi" => "14",
                "nama" => "KABUPATEN KEPULAUAN MERANTI",
            ],
            ["kode" => "1471", "kode_provinsi" => "14", "nama" => "KOTA PEKANBARU"],
            ["kode" => "1473", "kode_provinsi" => "14", "nama" => "KOTA D U M A I"],
            ["kode" => "1501", "kode_provinsi" => "15", "nama" => "KABUPATEN KERINCI"],
            ["kode" => "1502", "kode_provinsi" => "15", "nama" => "KABUPATEN MERANGIN"],
            [
                "kode" => "1503",
                "kode_provinsi" => "15",
                "nama" => "KABUPATEN SAROLANGUN",
            ],
            [
                "kode" => "1504",
                "kode_provinsi" => "15",
                "nama" => "KABUPATEN BATANG HARI",
            ],
            [
                "kode" => "1505",
                "kode_provinsi" => "15",
                "nama" => "KABUPATEN MUARO JAMBI",
            ],
            [
                "kode" => "1506",
                "kode_provinsi" => "15",
                "nama" => "KABUPATEN TANJUNG JABUNG TIMUR",
            ],
            [
                "kode" => "1507",
                "kode_provinsi" => "15",
                "nama" => "KABUPATEN TANJUNG JABUNG BARAT",
            ],
            ["kode" => "1508", "kode_provinsi" => "15", "nama" => "KABUPATEN TEBO"],
            ["kode" => "1509", "kode_provinsi" => "15", "nama" => "KABUPATEN BUNGO"],
            ["kode" => "1571", "kode_provinsi" => "15", "nama" => "KOTA JAMBI"],
            ["kode" => "1572", "kode_provinsi" => "15", "nama" => "KOTA SUNGAI PENUH"],
            [
                "kode" => "1601",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN OGAN KOMERING ULU",
            ],
            [
                "kode" => "1602",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN OGAN KOMERING ILIR",
            ],
            [
                "kode" => "1603",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN MUARA ENIM",
            ],
            ["kode" => "1604", "kode_provinsi" => "16", "nama" => "KABUPATEN LAHAT"],
            [
                "kode" => "1605",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN MUSI RAWAS",
            ],
            [
                "kode" => "1606",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN MUSI BANYUASIN",
            ],
            [
                "kode" => "1607",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN BANYU ASIN",
            ],
            [
                "kode" => "1608",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN OGAN KOMERING ULU SELATAN",
            ],
            [
                "kode" => "1609",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN OGAN KOMERING ULU TIMUR",
            ],
            [
                "kode" => "1610",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN OGAN ILIR",
            ],
            [
                "kode" => "1611",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN EMPAT LAWANG",
            ],
            [
                "kode" => "1612",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN PENUKAL ABAB LEMATANG ILIR",
            ],
            [
                "kode" => "1613",
                "kode_provinsi" => "16",
                "nama" => "KABUPATEN MUSI RAWAS UTARA",
            ],
            ["kode" => "1671", "kode_provinsi" => "16", "nama" => "KOTA PALEMBANG"],
            ["kode" => "1672", "kode_provinsi" => "16", "nama" => "KOTA PRABUMULIH"],
            ["kode" => "1673", "kode_provinsi" => "16", "nama" => "KOTA PAGAR ALAM"],
            ["kode" => "1674", "kode_provinsi" => "16", "nama" => "KOTA LUBUKLINGGAU"],
            [
                "kode" => "1701",
                "kode_provinsi" => "17",
                "nama" => "KABUPATEN BENGKULU SELATAN",
            ],
            [
                "kode" => "1702",
                "kode_provinsi" => "17",
                "nama" => "KABUPATEN REJANG LEBONG",
            ],
            [
                "kode" => "1703",
                "kode_provinsi" => "17",
                "nama" => "KABUPATEN BENGKULU UTARA",
            ],
            ["kode" => "1704", "kode_provinsi" => "17", "nama" => "KABUPATEN KAUR"],
            ["kode" => "1705", "kode_provinsi" => "17", "nama" => "KABUPATEN SELUMA"],
            ["kode" => "1706", "kode_provinsi" => "17", "nama" => "KABUPATEN MUKOMUKO"],
            ["kode" => "1707", "kode_provinsi" => "17", "nama" => "KABUPATEN LEBONG"],
            [
                "kode" => "1708",
                "kode_provinsi" => "17",
                "nama" => "KABUPATEN KEPAHIANG",
            ],
            [
                "kode" => "1709",
                "kode_provinsi" => "17",
                "nama" => "KABUPATEN BENGKULU TENGAH",
            ],
            ["kode" => "1771", "kode_provinsi" => "17", "nama" => "KOTA BENGKULU"],
            [
                "kode" => "1801",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN LAMPUNG BARAT",
            ],
            [
                "kode" => "1802",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN TANGGAMUS",
            ],
            [
                "kode" => "1803",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN LAMPUNG SELATAN",
            ],
            [
                "kode" => "1804",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN LAMPUNG TIMUR",
            ],
            [
                "kode" => "1805",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN LAMPUNG TENGAH",
            ],
            [
                "kode" => "1806",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN LAMPUNG UTARA",
            ],
            [
                "kode" => "1807",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN WAY KANAN",
            ],
            [
                "kode" => "1808",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN TULANGBAWANG",
            ],
            [
                "kode" => "1809",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN PESAWARAN",
            ],
            [
                "kode" => "1810",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN PRINGSEWU",
            ],
            ["kode" => "1811", "kode_provinsi" => "18", "nama" => "KABUPATEN MESUJI"],
            [
                "kode" => "1812",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN TULANG BAWANG BARAT",
            ],
            [
                "kode" => "1813",
                "kode_provinsi" => "18",
                "nama" => "KABUPATEN PESISIR BARAT",
            ],
            [
                "kode" => "1871",
                "kode_provinsi" => "18",
                "nama" => "KOTA BANDAR LAMPUNG",
            ],
            ["kode" => "1872", "kode_provinsi" => "18", "nama" => "KOTA METRO"],
            ["kode" => "1901", "kode_provinsi" => "19", "nama" => "KABUPATEN BANGKA"],
            ["kode" => "1902", "kode_provinsi" => "19", "nama" => "KABUPATEN BELITUNG"],
            [
                "kode" => "1903",
                "kode_provinsi" => "19",
                "nama" => "KABUPATEN BANGKA BARAT",
            ],
            [
                "kode" => "1904",
                "kode_provinsi" => "19",
                "nama" => "KABUPATEN BANGKA TENGAH",
            ],
            [
                "kode" => "1905",
                "kode_provinsi" => "19",
                "nama" => "KABUPATEN BANGKA SELATAN",
            ],
            [
                "kode" => "1906",
                "kode_provinsi" => "19",
                "nama" => "KABUPATEN BELITUNG TIMUR",
            ],
            [
                "kode" => "1971",
                "kode_provinsi" => "19",
                "nama" => "KOTA PANGKAL PINANG",
            ],
            ["kode" => "2101", "kode_provinsi" => "21", "nama" => "KABUPATEN KARIMUN"],
            ["kode" => "2102", "kode_provinsi" => "21", "nama" => "KABUPATEN BINTAN"],
            ["kode" => "2103", "kode_provinsi" => "21", "nama" => "KABUPATEN NATUNA"],
            ["kode" => "2104", "kode_provinsi" => "21", "nama" => "KABUPATEN LINGGA"],
            [
                "kode" => "2105",
                "kode_provinsi" => "21",
                "nama" => "KABUPATEN KEPULAUAN ANAMBAS",
            ],
            ["kode" => "2171", "kode_provinsi" => "21", "nama" => "KOTA BATAM"],
            [
                "kode" => "2172",
                "kode_provinsi" => "21",
                "nama" => "KOTA TANJUNG PINANG",
            ],
            [
                "kode" => "3101",
                "kode_provinsi" => "31",
                "nama" => "KABUPATEN KEPULAUAN SERIBU",
            ],
            [
                "kode" => "3171",
                "kode_provinsi" => "31",
                "nama" => "KOTA JAKARTA SELATAN",
            ],
            ["kode" => "3172", "kode_provinsi" => "31", "nama" => "KOTA JAKARTA TIMUR"],
            ["kode" => "3173", "kode_provinsi" => "31", "nama" => "KOTA JAKARTA PUSAT"],
            ["kode" => "3174", "kode_provinsi" => "31", "nama" => "KOTA JAKARTA BARAT"],
            ["kode" => "3175", "kode_provinsi" => "31", "nama" => "KOTA JAKARTA UTARA"],
            ["kode" => "3201", "kode_provinsi" => "32", "nama" => "KABUPATEN BOGOR"],
            ["kode" => "3202", "kode_provinsi" => "32", "nama" => "KABUPATEN SUKABUMI"],
            ["kode" => "3203", "kode_provinsi" => "32", "nama" => "KABUPATEN CIANJUR"],
            ["kode" => "3204", "kode_provinsi" => "32", "nama" => "KABUPATEN BANDUNG"],
            ["kode" => "3205", "kode_provinsi" => "32", "nama" => "KABUPATEN GARUT"],
            [
                "kode" => "3206",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN TASIKMALAYA",
            ],
            ["kode" => "3207", "kode_provinsi" => "32", "nama" => "KABUPATEN CIAMIS"],
            ["kode" => "3208", "kode_provinsi" => "32", "nama" => "KABUPATEN KUNINGAN"],
            ["kode" => "3209", "kode_provinsi" => "32", "nama" => "KABUPATEN CIREBON"],
            [
                "kode" => "3210",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN MAJALENGKA",
            ],
            ["kode" => "3211", "kode_provinsi" => "32", "nama" => "KABUPATEN SUMEDANG"],
            [
                "kode" => "3212",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN INDRAMAYU",
            ],
            ["kode" => "3213", "kode_provinsi" => "32", "nama" => "KABUPATEN SUBANG"],
            [
                "kode" => "3214",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN PURWAKARTA",
            ],
            ["kode" => "3215", "kode_provinsi" => "32", "nama" => "KABUPATEN KARAWANG"],
            ["kode" => "3216", "kode_provinsi" => "32", "nama" => "KABUPATEN BEKASI"],
            [
                "kode" => "3217",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN BANDUNG BARAT",
            ],
            [
                "kode" => "3218",
                "kode_provinsi" => "32",
                "nama" => "KABUPATEN PANGANDARAN",
            ],
            ["kode" => "3271", "kode_provinsi" => "32", "nama" => "KOTA BOGOR"],
            ["kode" => "3272", "kode_provinsi" => "32", "nama" => "KOTA SUKABUMI"],
            ["kode" => "3273", "kode_provinsi" => "32", "nama" => "KOTA BANDUNG"],
            ["kode" => "3274", "kode_provinsi" => "32", "nama" => "KOTA CIREBON"],
            ["kode" => "3275", "kode_provinsi" => "32", "nama" => "KOTA BEKASI"],
            ["kode" => "3276", "kode_provinsi" => "32", "nama" => "KOTA DEPOK"],
            ["kode" => "3277", "kode_provinsi" => "32", "nama" => "KOTA CIMAHI"],
            ["kode" => "3278", "kode_provinsi" => "32", "nama" => "KOTA TASIKMALAYA"],
            ["kode" => "3279", "kode_provinsi" => "32", "nama" => "KOTA BANJAR"],
            ["kode" => "3301", "kode_provinsi" => "33", "nama" => "KABUPATEN CILACAP"],
            ["kode" => "3302", "kode_provinsi" => "33", "nama" => "KABUPATEN BANYUMAS"],
            [
                "kode" => "3303",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN PURBALINGGA",
            ],
            [
                "kode" => "3304",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN BANJARNEGARA",
            ],
            ["kode" => "3305", "kode_provinsi" => "33", "nama" => "KABUPATEN KEBUMEN"],
            [
                "kode" => "3306",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN PURWOREJO",
            ],
            ["kode" => "3307", "kode_provinsi" => "33", "nama" => "KABUPATEN WONOSOBO"],
            ["kode" => "3308", "kode_provinsi" => "33", "nama" => "KABUPATEN MAGELANG"],
            ["kode" => "3309", "kode_provinsi" => "33", "nama" => "KABUPATEN BOYOLALI"],
            ["kode" => "3310", "kode_provinsi" => "33", "nama" => "KABUPATEN KLATEN"],
            [
                "kode" => "3311",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN SUKOHARJO",
            ],
            ["kode" => "3312", "kode_provinsi" => "33", "nama" => "KABUPATEN WONOGIRI"],
            [
                "kode" => "3313",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN KARANGANYAR",
            ],
            ["kode" => "3314", "kode_provinsi" => "33", "nama" => "KABUPATEN SRAGEN"],
            ["kode" => "3315", "kode_provinsi" => "33", "nama" => "KABUPATEN GROBOGAN"],
            ["kode" => "3316", "kode_provinsi" => "33", "nama" => "KABUPATEN BLORA"],
            ["kode" => "3317", "kode_provinsi" => "33", "nama" => "KABUPATEN REMBANG"],
            ["kode" => "3318", "kode_provinsi" => "33", "nama" => "KABUPATEN PATI"],
            ["kode" => "3319", "kode_provinsi" => "33", "nama" => "KABUPATEN KUDUS"],
            ["kode" => "3320", "kode_provinsi" => "33", "nama" => "KABUPATEN JEPARA"],
            ["kode" => "3321", "kode_provinsi" => "33", "nama" => "KABUPATEN DEMAK"],
            ["kode" => "3322", "kode_provinsi" => "33", "nama" => "KABUPATEN SEMARANG"],
            [
                "kode" => "3323",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN TEMANGGUNG",
            ],
            ["kode" => "3324", "kode_provinsi" => "33", "nama" => "KABUPATEN KENDAL"],
            ["kode" => "3325", "kode_provinsi" => "33", "nama" => "KABUPATEN BATANG"],
            [
                "kode" => "3326",
                "kode_provinsi" => "33",
                "nama" => "KABUPATEN PEKALONGAN",
            ],
            ["kode" => "3327", "kode_provinsi" => "33", "nama" => "KABUPATEN PEMALANG"],
            ["kode" => "3328", "kode_provinsi" => "33", "nama" => "KABUPATEN TEGAL"],
            ["kode" => "3329", "kode_provinsi" => "33", "nama" => "KABUPATEN BREBES"],
            ["kode" => "3371", "kode_provinsi" => "33", "nama" => "KOTA MAGELANG"],
            ["kode" => "3372", "kode_provinsi" => "33", "nama" => "KOTA SURAKARTA"],
            ["kode" => "3373", "kode_provinsi" => "33", "nama" => "KOTA SALATIGA"],
            ["kode" => "3374", "kode_provinsi" => "33", "nama" => "KOTA SEMARANG"],
            ["kode" => "3375", "kode_provinsi" => "33", "nama" => "KOTA PEKALONGAN"],
            ["kode" => "3376", "kode_provinsi" => "33", "nama" => "KOTA TEGAL"],
            [
                "kode" => "3401",
                "kode_provinsi" => "34",
                "nama" => "KABUPATEN KULON PROGO",
            ],
            ["kode" => "3402", "kode_provinsi" => "34", "nama" => "KABUPATEN BANTUL"],
            [
                "kode" => "3403",
                "kode_provinsi" => "34",
                "nama" => "KABUPATEN GUNUNG KIDUL",
            ],
            ["kode" => "3404", "kode_provinsi" => "34", "nama" => "KABUPATEN SLEMAN"],
            ["kode" => "3471", "kode_provinsi" => "34", "nama" => "KOTA YOGYAKARTA"],
            ["kode" => "3501", "kode_provinsi" => "35", "nama" => "KABUPATEN PACITAN"],
            ["kode" => "3502", "kode_provinsi" => "35", "nama" => "KABUPATEN PONOROGO"],
            [
                "kode" => "3503",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN TRENGGALEK",
            ],
            [
                "kode" => "3504",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN TULUNGAGUNG",
            ],
            ["kode" => "3505", "kode_provinsi" => "35", "nama" => "KABUPATEN BLITAR"],
            ["kode" => "3506", "kode_provinsi" => "35", "nama" => "KABUPATEN KEDIRI"],
            ["kode" => "3507", "kode_provinsi" => "35", "nama" => "KABUPATEN MALANG"],
            ["kode" => "3508", "kode_provinsi" => "35", "nama" => "KABUPATEN LUMAJANG"],
            ["kode" => "3509", "kode_provinsi" => "35", "nama" => "KABUPATEN JEMBER"],
            [
                "kode" => "3510",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN BANYUWANGI",
            ],
            [
                "kode" => "3511",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN BONDOWOSO",
            ],
            [
                "kode" => "3512",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN SITUBONDO",
            ],
            [
                "kode" => "3513",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN PROBOLINGGO",
            ],
            ["kode" => "3514", "kode_provinsi" => "35", "nama" => "KABUPATEN PASURUAN"],
            ["kode" => "3515", "kode_provinsi" => "35", "nama" => "KABUPATEN SIDOARJO"],
            [
                "kode" => "3516",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN MOJOKERTO",
            ],
            ["kode" => "3517", "kode_provinsi" => "35", "nama" => "KABUPATEN JOMBANG"],
            ["kode" => "3518", "kode_provinsi" => "35", "nama" => "KABUPATEN NGANJUK"],
            ["kode" => "3519", "kode_provinsi" => "35", "nama" => "KABUPATEN MADIUN"],
            ["kode" => "3520", "kode_provinsi" => "35", "nama" => "KABUPATEN MAGETAN"],
            ["kode" => "3521", "kode_provinsi" => "35", "nama" => "KABUPATEN NGAWI"],
            [
                "kode" => "3522",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN BOJONEGORO",
            ],
            ["kode" => "3523", "kode_provinsi" => "35", "nama" => "KABUPATEN TUBAN"],
            ["kode" => "3524", "kode_provinsi" => "35", "nama" => "KABUPATEN LAMONGAN"],
            ["kode" => "3525", "kode_provinsi" => "35", "nama" => "KABUPATEN GRESIK"],
            [
                "kode" => "3526",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN BANGKALAN",
            ],
            ["kode" => "3527", "kode_provinsi" => "35", "nama" => "KABUPATEN SAMPANG"],
            [
                "kode" => "3528",
                "kode_provinsi" => "35",
                "nama" => "KABUPATEN PAMEKASAN",
            ],
            ["kode" => "3529", "kode_provinsi" => "35", "nama" => "KABUPATEN SUMENEP"],
            ["kode" => "3571", "kode_provinsi" => "35", "nama" => "KOTA KEDIRI"],
            ["kode" => "3572", "kode_provinsi" => "35", "nama" => "KOTA BLITAR"],
            ["kode" => "3573", "kode_provinsi" => "35", "nama" => "KOTA MALANG"],
            ["kode" => "3574", "kode_provinsi" => "35", "nama" => "KOTA PROBOLINGGO"],
            ["kode" => "3575", "kode_provinsi" => "35", "nama" => "KOTA PASURUAN"],
            ["kode" => "3576", "kode_provinsi" => "35", "nama" => "KOTA MOJOKERTO"],
            ["kode" => "3577", "kode_provinsi" => "35", "nama" => "KOTA MADIUN"],
            ["kode" => "3578", "kode_provinsi" => "35", "nama" => "KOTA SURABAYA"],
            ["kode" => "3579", "kode_provinsi" => "35", "nama" => "KOTA BATU"],
            [
                "kode" => "3601",
                "kode_provinsi" => "36",
                "nama" => "KABUPATEN PANDEGLANG",
            ],
            ["kode" => "3602", "kode_provinsi" => "36", "nama" => "KABUPATEN LEBAK"],
            [
                "kode" => "3603",
                "kode_provinsi" => "36",
                "nama" => "KABUPATEN TANGERANG",
            ],
            ["kode" => "3604", "kode_provinsi" => "36", "nama" => "KABUPATEN SERANG"],
            ["kode" => "3671", "kode_provinsi" => "36", "nama" => "KOTA TANGERANG"],
            ["kode" => "3672", "kode_provinsi" => "36", "nama" => "KOTA CILEGON"],
            ["kode" => "3673", "kode_provinsi" => "36", "nama" => "KOTA SERANG"],
            [
                "kode" => "3674",
                "kode_provinsi" => "36",
                "nama" => "KOTA TANGERANG SELATAN",
            ],
            ["kode" => "5101", "kode_provinsi" => "51", "nama" => "KABUPATEN JEMBRANA"],
            ["kode" => "5102", "kode_provinsi" => "51", "nama" => "KABUPATEN TABANAN"],
            ["kode" => "5103", "kode_provinsi" => "51", "nama" => "KABUPATEN BADUNG"],
            ["kode" => "5104", "kode_provinsi" => "51", "nama" => "KABUPATEN GIANYAR"],
            [
                "kode" => "5105",
                "kode_provinsi" => "51",
                "nama" => "KABUPATEN KLUNGKUNG",
            ],
            ["kode" => "5106", "kode_provinsi" => "51", "nama" => "KABUPATEN BANGLI"],
            [
                "kode" => "5107",
                "kode_provinsi" => "51",
                "nama" => "KABUPATEN KARANG ASEM",
            ],
            ["kode" => "5108", "kode_provinsi" => "51", "nama" => "KABUPATEN BULELENG"],
            ["kode" => "5171", "kode_provinsi" => "51", "nama" => "KOTA DENPASAR"],
            [
                "kode" => "5201",
                "kode_provinsi" => "52",
                "nama" => "KABUPATEN LOMBOK BARAT",
            ],
            [
                "kode" => "5202",
                "kode_provinsi" => "52",
                "nama" => "KABUPATEN LOMBOK TENGAH",
            ],
            [
                "kode" => "5203",
                "kode_provinsi" => "52",
                "nama" => "KABUPATEN LOMBOK TIMUR",
            ],
            ["kode" => "5204", "kode_provinsi" => "52", "nama" => "KABUPATEN SUMBAWA"],
            ["kode" => "5205", "kode_provinsi" => "52", "nama" => "KABUPATEN DOMPU"],
            ["kode" => "5206", "kode_provinsi" => "52", "nama" => "KABUPATEN BIMA"],
            [
                "kode" => "5207",
                "kode_provinsi" => "52",
                "nama" => "KABUPATEN SUMBAWA BARAT",
            ],
            [
                "kode" => "5208",
                "kode_provinsi" => "52",
                "nama" => "KABUPATEN LOMBOK UTARA",
            ],
            ["kode" => "5271", "kode_provinsi" => "52", "nama" => "KOTA MATARAM"],
            ["kode" => "5272", "kode_provinsi" => "52", "nama" => "KOTA BIMA"],
            [
                "kode" => "5301",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN SUMBA BARAT",
            ],
            [
                "kode" => "5302",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN SUMBA TIMUR",
            ],
            ["kode" => "5303", "kode_provinsi" => "53", "nama" => "KABUPATEN KUPANG"],
            [
                "kode" => "5304",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN TIMOR TENGAH SELATAN",
            ],
            [
                "kode" => "5305",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN TIMOR TENGAH UTARA",
            ],
            ["kode" => "5306", "kode_provinsi" => "53", "nama" => "KABUPATEN BELU"],
            ["kode" => "5307", "kode_provinsi" => "53", "nama" => "KABUPATEN ALOR"],
            ["kode" => "5308", "kode_provinsi" => "53", "nama" => "KABUPATEN LEMBATA"],
            [
                "kode" => "5309",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN FLORES TIMUR",
            ],
            ["kode" => "5310", "kode_provinsi" => "53", "nama" => "KABUPATEN SIKKA"],
            ["kode" => "5311", "kode_provinsi" => "53", "nama" => "KABUPATEN ENDE"],
            ["kode" => "5312", "kode_provinsi" => "53", "nama" => "KABUPATEN NGADA"],
            [
                "kode" => "5313",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN MANGGARAI",
            ],
            [
                "kode" => "5314",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN ROTE NDAO",
            ],
            [
                "kode" => "5315",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN MANGGARAI BARAT",
            ],
            [
                "kode" => "5316",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN SUMBA TENGAH",
            ],
            [
                "kode" => "5317",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN SUMBA BARAT DAYA",
            ],
            ["kode" => "5318", "kode_provinsi" => "53", "nama" => "KABUPATEN NAGEKEO"],
            [
                "kode" => "5319",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN MANGGARAI TIMUR",
            ],
            [
                "kode" => "5320",
                "kode_provinsi" => "53",
                "nama" => "KABUPATEN SABU RAIJUA",
            ],
            ["kode" => "5321", "kode_provinsi" => "53", "nama" => "KABUPATEN MALAKA"],
            ["kode" => "5371", "kode_provinsi" => "53", "nama" => "KOTA KUPANG"],
            ["kode" => "6101", "kode_provinsi" => "61", "nama" => "KABUPATEN SAMBAS"],
            [
                "kode" => "6102",
                "kode_provinsi" => "61",
                "nama" => "KABUPATEN BENGKAYANG",
            ],
            ["kode" => "6103", "kode_provinsi" => "61", "nama" => "KABUPATEN LANDAK"],
            ["kode" => "6104", "kode_provinsi" => "61", "nama" => "KABUPATEN MEMPAWAH"],
            ["kode" => "6105", "kode_provinsi" => "61", "nama" => "KABUPATEN SANGGAU"],
            ["kode" => "6106", "kode_provinsi" => "61", "nama" => "KABUPATEN KETAPANG"],
            ["kode" => "6107", "kode_provinsi" => "61", "nama" => "KABUPATEN SINTANG"],
            [
                "kode" => "6108",
                "kode_provinsi" => "61",
                "nama" => "KABUPATEN KAPUAS HULU",
            ],
            ["kode" => "6109", "kode_provinsi" => "61", "nama" => "KABUPATEN SEKADAU"],
            ["kode" => "6110", "kode_provinsi" => "61", "nama" => "KABUPATEN MELAWI"],
            [
                "kode" => "6111",
                "kode_provinsi" => "61",
                "nama" => "KABUPATEN KAYONG UTARA",
            ],
            [
                "kode" => "6112",
                "kode_provinsi" => "61",
                "nama" => "KABUPATEN KUBU RAYA",
            ],
            ["kode" => "6171", "kode_provinsi" => "61", "nama" => "KOTA PONTIANAK"],
            ["kode" => "6172", "kode_provinsi" => "61", "nama" => "KOTA SINGKAWANG"],
            [
                "kode" => "6201",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN KOTAWARINGIN BARAT",
            ],
            [
                "kode" => "6202",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN KOTAWARINGIN TIMUR",
            ],
            ["kode" => "6203", "kode_provinsi" => "62", "nama" => "KABUPATEN KAPUAS"],
            [
                "kode" => "6204",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN BARITO SELATAN",
            ],
            [
                "kode" => "6205",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN BARITO UTARA",
            ],
            ["kode" => "6206", "kode_provinsi" => "62", "nama" => "KABUPATEN SUKAMARA"],
            ["kode" => "6207", "kode_provinsi" => "62", "nama" => "KABUPATEN LAMANDAU"],
            ["kode" => "6208", "kode_provinsi" => "62", "nama" => "KABUPATEN SERUYAN"],
            ["kode" => "6209", "kode_provinsi" => "62", "nama" => "KABUPATEN KATINGAN"],
            [
                "kode" => "6210",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN PULANG PISAU",
            ],
            [
                "kode" => "6211",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN GUNUNG MAS",
            ],
            [
                "kode" => "6212",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN BARITO TIMUR",
            ],
            [
                "kode" => "6213",
                "kode_provinsi" => "62",
                "nama" => "KABUPATEN MURUNG RAYA",
            ],
            ["kode" => "6271", "kode_provinsi" => "62", "nama" => "KOTA PALANGKA RAYA"],
            [
                "kode" => "6301",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN TANAH LAUT",
            ],
            [
                "kode" => "6302",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN KOTA BARU",
            ],
            ["kode" => "6303", "kode_provinsi" => "63", "nama" => "KABUPATEN BANJAR"],
            [
                "kode" => "6304",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN BARITO KUALA",
            ],
            ["kode" => "6305", "kode_provinsi" => "63", "nama" => "KABUPATEN TAPIN"],
            [
                "kode" => "6306",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN HULU SUNGAI SELATAN",
            ],
            [
                "kode" => "6307",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN HULU SUNGAI TENGAH",
            ],
            [
                "kode" => "6308",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN HULU SUNGAI UTARA",
            ],
            ["kode" => "6309", "kode_provinsi" => "63", "nama" => "KABUPATEN TABALONG"],
            [
                "kode" => "6310",
                "kode_provinsi" => "63",
                "nama" => "KABUPATEN TANAH BUMBU",
            ],
            ["kode" => "6311", "kode_provinsi" => "63", "nama" => "KABUPATEN BALANGAN"],
            ["kode" => "6371", "kode_provinsi" => "63", "nama" => "KOTA BANJARMASIN"],
            ["kode" => "6372", "kode_provinsi" => "63", "nama" => "KOTA BANJAR BARU"],
            ["kode" => "6401", "kode_provinsi" => "64", "nama" => "KABUPATEN PASER"],
            [
                "kode" => "6402",
                "kode_provinsi" => "64",
                "nama" => "KABUPATEN KUTAI BARAT",
            ],
            [
                "kode" => "6403",
                "kode_provinsi" => "64",
                "nama" => "KABUPATEN KUTAI KARTANEGARA",
            ],
            [
                "kode" => "6404",
                "kode_provinsi" => "64",
                "nama" => "KABUPATEN KUTAI TIMUR",
            ],
            ["kode" => "6405", "kode_provinsi" => "64", "nama" => "KABUPATEN BERAU"],
            [
                "kode" => "6409",
                "kode_provinsi" => "64",
                "nama" => "KABUPATEN PENAJAM PASER UTARA",
            ],
            [
                "kode" => "6411",
                "kode_provinsi" => "64",
                "nama" => "KABUPATEN MAHAKAM HULU",
            ],
            ["kode" => "6471", "kode_provinsi" => "64", "nama" => "KOTA BALIKPAPAN"],
            ["kode" => "6472", "kode_provinsi" => "64", "nama" => "KOTA SAMARINDA"],
            ["kode" => "6474", "kode_provinsi" => "64", "nama" => "KOTA BONTANG"],
            ["kode" => "6501", "kode_provinsi" => "65", "nama" => "KABUPATEN MALINAU"],
            ["kode" => "6502", "kode_provinsi" => "65", "nama" => "KABUPATEN BULUNGAN"],
            [
                "kode" => "6503",
                "kode_provinsi" => "65",
                "nama" => "KABUPATEN TANA TIDUNG",
            ],
            ["kode" => "6504", "kode_provinsi" => "65", "nama" => "KABUPATEN NUNUKAN"],
            ["kode" => "6571", "kode_provinsi" => "65", "nama" => "KOTA TARAKAN"],
            [
                "kode" => "7101",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN BOLAANG MONGONDOW",
            ],
            ["kode" => "7102", "kode_provinsi" => "71", "nama" => "KABUPATEN MINAHASA"],
            [
                "kode" => "7103",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN KEPULAUAN SANGIHE",
            ],
            [
                "kode" => "7104",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN KEPULAUAN TALAUD",
            ],
            [
                "kode" => "7105",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN MINAHASA SELATAN",
            ],
            [
                "kode" => "7106",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN MINAHASA UTARA",
            ],
            [
                "kode" => "7107",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN BOLAANG MONGONDOW UTARA",
            ],
            [
                "kode" => "7108",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN SIAU TAGULANDANG BIARO",
            ],
            [
                "kode" => "7109",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN MINAHASA TENGGARA",
            ],
            [
                "kode" => "7110",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN BOLAANG MONGONDOW SELATAN",
            ],
            [
                "kode" => "7111",
                "kode_provinsi" => "71",
                "nama" => "KABUPATEN BOLAANG MONGONDOW TIMUR",
            ],
            ["kode" => "7171", "kode_provinsi" => "71", "nama" => "KOTA MANADO"],
            ["kode" => "7172", "kode_provinsi" => "71", "nama" => "KOTA BITUNG"],
            ["kode" => "7173", "kode_provinsi" => "71", "nama" => "KOTA TOMOHON"],
            ["kode" => "7174", "kode_provinsi" => "71", "nama" => "KOTA KOTAMOBAGU"],
            [
                "kode" => "7201",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN BANGGAI KEPULAUAN",
            ],
            ["kode" => "7202", "kode_provinsi" => "72", "nama" => "KABUPATEN BANGGAI"],
            ["kode" => "7203", "kode_provinsi" => "72", "nama" => "KABUPATEN MOROWALI"],
            ["kode" => "7204", "kode_provinsi" => "72", "nama" => "KABUPATEN POSO"],
            ["kode" => "7205", "kode_provinsi" => "72", "nama" => "KABUPATEN DONGGALA"],
            [
                "kode" => "7206",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN TOLI-TOLI",
            ],
            ["kode" => "7207", "kode_provinsi" => "72", "nama" => "KABUPATEN BUOL"],
            [
                "kode" => "7208",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN PARIGI MOUTONG",
            ],
            [
                "kode" => "7209",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN TOJO UNA-UNA",
            ],
            ["kode" => "7210", "kode_provinsi" => "72", "nama" => "KABUPATEN SIGI"],
            [
                "kode" => "7211",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN BANGGAI LAUT",
            ],
            [
                "kode" => "7212",
                "kode_provinsi" => "72",
                "nama" => "KABUPATEN MOROWALI UTARA",
            ],
            ["kode" => "7271", "kode_provinsi" => "72", "nama" => "KOTA PALU"],
            [
                "kode" => "7301",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN KEPULAUAN SELAYAR",
            ],
            [
                "kode" => "7302",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN BULUKUMBA",
            ],
            ["kode" => "7303", "kode_provinsi" => "73", "nama" => "KABUPATEN BANTAENG"],
            [
                "kode" => "7304",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN JENEPONTO",
            ],
            ["kode" => "7305", "kode_provinsi" => "73", "nama" => "KABUPATEN TAKALAR"],
            ["kode" => "7306", "kode_provinsi" => "73", "nama" => "KABUPATEN GOWA"],
            ["kode" => "7307", "kode_provinsi" => "73", "nama" => "KABUPATEN SINJAI"],
            ["kode" => "7308", "kode_provinsi" => "73", "nama" => "KABUPATEN MAROS"],
            [
                "kode" => "7309",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN PANGKAJENE DAN KEPULAUAN",
            ],
            ["kode" => "7310", "kode_provinsi" => "73", "nama" => "KABUPATEN BARRU"],
            ["kode" => "7311", "kode_provinsi" => "73", "nama" => "KABUPATEN BONE"],
            ["kode" => "7312", "kode_provinsi" => "73", "nama" => "KABUPATEN SOPPENG"],
            ["kode" => "7313", "kode_provinsi" => "73", "nama" => "KABUPATEN WAJO"],
            [
                "kode" => "7314",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN SIDENRENG RAPPANG",
            ],
            ["kode" => "7315", "kode_provinsi" => "73", "nama" => "KABUPATEN PINRANG"],
            ["kode" => "7316", "kode_provinsi" => "73", "nama" => "KABUPATEN ENREKANG"],
            ["kode" => "7317", "kode_provinsi" => "73", "nama" => "KABUPATEN LUWU"],
            [
                "kode" => "7318",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN TANA TORAJA",
            ],
            [
                "kode" => "7322",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN LUWU UTARA",
            ],
            [
                "kode" => "7325",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN LUWU TIMUR",
            ],
            [
                "kode" => "7326",
                "kode_provinsi" => "73",
                "nama" => "KABUPATEN TORAJA UTARA",
            ],
            ["kode" => "7371", "kode_provinsi" => "73", "nama" => "KOTA MAKASSAR"],
            ["kode" => "7372", "kode_provinsi" => "73", "nama" => "KOTA PAREPARE"],
            ["kode" => "7373", "kode_provinsi" => "73", "nama" => "KOTA PALOPO"],
            ["kode" => "7401", "kode_provinsi" => "74", "nama" => "KABUPATEN BUTON"],
            ["kode" => "7402", "kode_provinsi" => "74", "nama" => "KABUPATEN MUNA"],
            ["kode" => "7403", "kode_provinsi" => "74", "nama" => "KABUPATEN KONAWE"],
            ["kode" => "7404", "kode_provinsi" => "74", "nama" => "KABUPATEN KOLAKA"],
            [
                "kode" => "7405",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN KONAWE SELATAN",
            ],
            ["kode" => "7406", "kode_provinsi" => "74", "nama" => "KABUPATEN BOMBANA"],
            ["kode" => "7407", "kode_provinsi" => "74", "nama" => "KABUPATEN WAKATOBI"],
            [
                "kode" => "7408",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN KOLAKA UTARA",
            ],
            [
                "kode" => "7409",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN BUTON UTARA",
            ],
            [
                "kode" => "7410",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN KONAWE UTARA",
            ],
            [
                "kode" => "7411",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN KOLAKA TIMUR",
            ],
            [
                "kode" => "7412",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN KONAWE KEPULAUAN",
            ],
            [
                "kode" => "7413",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN MUNA BARAT",
            ],
            [
                "kode" => "7414",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN BUTON TENGAH",
            ],
            [
                "kode" => "7415",
                "kode_provinsi" => "74",
                "nama" => "KABUPATEN BUTON SELATAN",
            ],
            ["kode" => "7471", "kode_provinsi" => "74", "nama" => "KOTA KENDARI"],
            ["kode" => "7472", "kode_provinsi" => "74", "nama" => "KOTA BAUBAU"],
            ["kode" => "7501", "kode_provinsi" => "75", "nama" => "KABUPATEN BOALEMO"],
            [
                "kode" => "7502",
                "kode_provinsi" => "75",
                "nama" => "KABUPATEN GORONTALO",
            ],
            ["kode" => "7503", "kode_provinsi" => "75", "nama" => "KABUPATEN POHUWATO"],
            [
                "kode" => "7504",
                "kode_provinsi" => "75",
                "nama" => "KABUPATEN BONE BOLANGO",
            ],
            [
                "kode" => "7505",
                "kode_provinsi" => "75",
                "nama" => "KABUPATEN GORONTALO UTARA",
            ],
            ["kode" => "7571", "kode_provinsi" => "75", "nama" => "KOTA GORONTALO"],
            ["kode" => "7601", "kode_provinsi" => "76", "nama" => "KABUPATEN MAJENE"],
            [
                "kode" => "7602",
                "kode_provinsi" => "76",
                "nama" => "KABUPATEN POLEWALI MANDAR",
            ],
            ["kode" => "7603", "kode_provinsi" => "76", "nama" => "KABUPATEN MAMASA"],
            ["kode" => "7604", "kode_provinsi" => "76", "nama" => "KABUPATEN MAMUJU"],
            [
                "kode" => "7605",
                "kode_provinsi" => "76",
                "nama" => "KABUPATEN MAMUJU UTARA",
            ],
            [
                "kode" => "7606",
                "kode_provinsi" => "76",
                "nama" => "KABUPATEN MAMUJU TENGAH",
            ],
            [
                "kode" => "8101",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN MALUKU TENGGARA BARAT",
            ],
            [
                "kode" => "8102",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN MALUKU TENGGARA",
            ],
            [
                "kode" => "8103",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN MALUKU TENGAH",
            ],
            ["kode" => "8104", "kode_provinsi" => "81", "nama" => "KABUPATEN BURU"],
            [
                "kode" => "8105",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN KEPULAUAN ARU",
            ],
            [
                "kode" => "8106",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN SERAM BAGIAN BARAT",
            ],
            [
                "kode" => "8107",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN SERAM BAGIAN TIMUR",
            ],
            [
                "kode" => "8108",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN MALUKU BARAT DAYA",
            ],
            [
                "kode" => "8109",
                "kode_provinsi" => "81",
                "nama" => "KABUPATEN BURU SELATAN",
            ],
            ["kode" => "8171", "kode_provinsi" => "81", "nama" => "KOTA AMBON"],
            ["kode" => "8172", "kode_provinsi" => "81", "nama" => "KOTA TUAL"],
            [
                "kode" => "8201",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN HALMAHERA BARAT",
            ],
            [
                "kode" => "8202",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN HALMAHERA TENGAH",
            ],
            [
                "kode" => "8203",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN KEPULAUAN SULA",
            ],
            [
                "kode" => "8204",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN HALMAHERA SELATAN",
            ],
            [
                "kode" => "8205",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN HALMAHERA UTARA",
            ],
            [
                "kode" => "8206",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN HALMAHERA TIMUR",
            ],
            [
                "kode" => "8207",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN PULAU MOROTAI",
            ],
            [
                "kode" => "8208",
                "kode_provinsi" => "82",
                "nama" => "KABUPATEN PULAU TALIABU",
            ],
            ["kode" => "8271", "kode_provinsi" => "82", "nama" => "KOTA TERNATE"],
            [
                "kode" => "8272",
                "kode_provinsi" => "82",
                "nama" => "KOTA TIDORE KEPULAUAN",
            ],
            ["kode" => "9101", "kode_provinsi" => "91", "nama" => "KABUPATEN FAKFAK"],
            ["kode" => "9102", "kode_provinsi" => "91", "nama" => "KABUPATEN KAIMANA"],
            [
                "kode" => "9103",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN TELUK WONDAMA",
            ],
            [
                "kode" => "9104",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN TELUK BINTUNI",
            ],
            [
                "kode" => "9105",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN MANOKWARI",
            ],
            [
                "kode" => "9106",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN SORONG SELATAN",
            ],
            ["kode" => "9107", "kode_provinsi" => "91", "nama" => "KABUPATEN SORONG"],
            [
                "kode" => "9108",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN RAJA AMPAT",
            ],
            ["kode" => "9109", "kode_provinsi" => "91", "nama" => "KABUPATEN TAMBRAUW"],
            ["kode" => "9110", "kode_provinsi" => "91", "nama" => "KABUPATEN MAYBRAT"],
            [
                "kode" => "9111",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN MANOKWARI SELATAN",
            ],
            [
                "kode" => "9112",
                "kode_provinsi" => "91",
                "nama" => "KABUPATEN PEGUNUNGAN ARFAK",
            ],
            ["kode" => "9171", "kode_provinsi" => "91", "nama" => "KOTA SORONG"],
            ["kode" => "9401", "kode_provinsi" => "94", "nama" => "KABUPATEN MERAUKE"],
            [
                "kode" => "9402",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN JAYAWIJAYA",
            ],
            ["kode" => "9403", "kode_provinsi" => "94", "nama" => "KABUPATEN JAYAPURA"],
            ["kode" => "9404", "kode_provinsi" => "94", "nama" => "KABUPATEN NABIRE"],
            [
                "kode" => "9408",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN KEPULAUAN YAPEN",
            ],
            [
                "kode" => "9409",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN BIAK NUMFOR",
            ],
            ["kode" => "9410", "kode_provinsi" => "94", "nama" => "KABUPATEN PANIAI"],
            [
                "kode" => "9411",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN PUNCAK JAYA",
            ],
            ["kode" => "9412", "kode_provinsi" => "94", "nama" => "KABUPATEN MIMIKA"],
            [
                "kode" => "9413",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN BOVEN DIGOEL",
            ],
            ["kode" => "9414", "kode_provinsi" => "94", "nama" => "KABUPATEN MAPPI"],
            ["kode" => "9415", "kode_provinsi" => "94", "nama" => "KABUPATEN ASMAT"],
            ["kode" => "9416", "kode_provinsi" => "94", "nama" => "KABUPATEN YAHUKIMO"],
            [
                "kode" => "9417",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN PEGUNUNGAN BINTANG",
            ],
            ["kode" => "9418", "kode_provinsi" => "94", "nama" => "KABUPATEN TOLIKARA"],
            ["kode" => "9419", "kode_provinsi" => "94", "nama" => "KABUPATEN SARMI"],
            ["kode" => "9420", "kode_provinsi" => "94", "nama" => "KABUPATEN KEEROM"],
            ["kode" => "9426", "kode_provinsi" => "94", "nama" => "KABUPATEN WAROPEN"],
            ["kode" => "9427", "kode_provinsi" => "94", "nama" => "KABUPATEN SUPIORI"],
            [
                "kode" => "9428",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN MAMBERAMO RAYA",
            ],
            ["kode" => "9429", "kode_provinsi" => "94", "nama" => "KABUPATEN NDUGA"],
            [
                "kode" => "9430",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN LANNY JAYA",
            ],
            [
                "kode" => "9431",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN MAMBERAMO TENGAH",
            ],
            ["kode" => "9432", "kode_provinsi" => "94", "nama" => "KABUPATEN YALIMO"],
            ["kode" => "9433", "kode_provinsi" => "94", "nama" => "KABUPATEN PUNCAK"],
            ["kode" => "9434", "kode_provinsi" => "94", "nama" => "KABUPATEN DOGIYAI"],
            [
                "kode" => "9435",
                "kode_provinsi" => "94",
                "nama" => "KABUPATEN INTAN JAYA",
            ],
            ["kode" => "9436", "kode_provinsi" => "94", "nama" => "KABUPATEN DEIYAI"],
            ["kode" => "9471", "kode_provinsi" => "94", "nama" => "KOTA JAYAPURA"],
        ];

        foreach($refKabupatenKota as $kabupatenKota){
            $provinsi = Provinsi::where('kode', $kabupatenKota['kode_provinsi'])->first();
            KabupatenKota::firstOrCreate([
                'kode' => $kabupatenKota['kode'],
                'provinsi_id' => $provinsi->id,
                'nama' => $kabupatenKota['nama'],
            ]);
        }
    }
}
